### ISSUE TITLE
Filtering commits

### ISSUE THREAD

**Issue by m-dubois** [danielflower/maven-gitlog-plugin#35]
Hello! :)

I wondered of there was a way to filter the commits to display in the changelog?

Some of the commits have no meaning or no interest for the end user and I would like to have a way to specify to the plugin to ignore some of the commits. To exclude or to include... either way :)

Maybe with a pattern similar to:
<bugzillaPattern>(?:Bug|UPDATE|FIX|ADD|NEW|#) ?#?(\d+)</bugzillaPattern>

That's close to what @aelamrani asked in the issue #23 ... and may actually be complementary.

Oh and btw... thanks a lot for this plugin :)

**Comment by poznachowski** [comment]
#36 may suits your needs.

**Comment by danielflower** [comment]
Added in 1.12.3
