### ISSUE TITLE
integration with maven reporting

### ISSUE THREAD

**Issue by jasond** [danielflower/maven-gitlog-plugin#9]
hi,

nice plugin you have here, well done!

do you have any plans to extend it a bit more to hook up with the maven reporting workflow?

http://docs.codehaus.org/display/MAVENUSER/Write+your+own+report+plugin 

cheers

j

**Comment by danielflower** [comment]
Only took 3 years, but here you go.... https://github.com/danielflower/maven-gitlog-plugin/pull/33
